site_name: LTA 2nd DevOps Immersion Programme - React Web App Demo
theme:
  name: material
  features:
    - instant
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
nav:
  - Home:
      - index.md
      - 2_base.md
      - 3_card.md
      - 4_components.md
